Try suppress naming warnings from linter
```
  Running [/home/runner/golangci-lint-2.10.1-linux-amd64/golangci-lint config path] in [/home/runner/work/infra/infra] ...
  Running [/home/runner/golangci-lint-2.10.1-linux-amd64/golangci-lint config verify] in [/home/runner/work/infra/infra] ...
  Running [/home/runner/golangci-lint-2.10.1-linux-amd64/golangci-lint run] in [/home/runner/work/infra/infra] ...
  Error: cmd/infractl/flavor/list/fancy.go:1:9: var-naming: avoid package names that conflict with Go standard library package names (revive)
  package list
          ^
  Error: pkg/buildinfo/buildinfo.go:3:9: var-naming: avoid package names that conflict with Go standard library package names (revive)
  package buildinfo
          ^
  Error: pkg/service/metrics/metrics.go:2:9: var-naming: avoid package names that conflict with Go standard library package names (revive)
  package metrics
          ^
  3 issues:
  * revive: 3

  Error: issues found
```

https://github.com/stackrox/infra/actions/runs/22721785912/job/65885650995?pr=1768#step:4:40
I did not break those, I did not even touch them.

Confirmed they started failing on no-op PR, see
https://github.com/stackrox/infra/pull/1769 and
https://github.com/stackrox/infra/actions/runs/22730204288/job/65916882489?pr=1769
Not sure why `master` wasn't affected.

Suppressing.

Used these docs
https://golangci-lint.run/docs/linters/false-positives/#exclude-issues-by-path

I tried `package blah //nolint:var-naming` but that did not work.
I did not do
```
//nolint:var-naming
package blah
```
because that would turn off the rule for the entire file.